export declare const SCALE_TYPES: {
    ZOOM: string;
    SCALE: string;
};
export declare const ENTITY_STATUS_MAP: {
    available: string;
    unavailable: string;
    selected: string;
    preferred: string;
    extra: string;
    disabled: string;
};
export declare const ENTITY_TYPE_MAP: {
    seat: string;
    aisle: string;
    empty: string;
    index: string;
};
export declare const ENTITY_SCHEME_MAP: {
    seat: string;
    empty: string;
    aisle: string;
};
export declare const CLASS_CODE_MAP: Record<string, string>;
export declare const LOCALES_MAP: Record<string, Record<string, string>>;
export declare const DEFAULT_LANG = "EN";
export declare const DEFAULT_UNITS = "metric";
export declare const DEFAULT_SCALE_TYPE: string;
export declare const DEFAULT_AUTHORIZATION_SCHEME = "Bearer";
export declare const DEFAULT_SEAT_MARGIN = 3;
export declare const DEFAULT_SEAT_MAP_WIDTH = 350;
export declare const DEFAULT_HORIZONTAL_LAYOUT = false;
export declare const DEFAULT_VISIBLE_HULL = false;
export declare const DEFAULT_VISIBLE_WINGS = false;
export declare const DEFAULT_VISIBLE_CABIN_TITLES = false;
export declare const DEFAULT_BUILT_IN_TOOLTIP = true;
export declare const DEFAULT_EXTERNAL_PASSENGER_MANAGEMENT = false;
export declare const DEFAULT_SHOW_DECK_SELECTOR = true;
export declare const DEFAULT_SINGLE_DECK_MODE = true;
export declare const DEFAULT_TOOLTIP_ON_HOVER = false;
export declare const DEFAULT_RTL = false;
export declare const DEFAULT_TOOLTIP_WIDTH = 260;
export declare const DEFAULT_SEAT_PASSENGER_TYPES: string[];
export declare const DEFAULT_FEATURES_RENDER_LIMIT = 12;
export declare const FUSELAGE_HEIGHT_TO_WIDTH_RATIO = 1.4;
export declare const SEAT_MAP_WIDTH_TO_WINGS_WIDTH_RATIO = 4;
export declare const SEAT_SIZE_BY_TYPE: [number, number][];
export declare const DEFAULT_SEAT_SIZE: {
    width: number;
    height: number;
};
export declare const DEFAULT_SEAT_CLASS = "E";
export declare const DEFAULT_DECK_PADDING_SIZE = 10;
export declare const DEFAULT_DECK_TITLE_HEIGHT = 80;
export declare const DEFAULT_INDEX_ROW_HEIGHT = 120;
export declare const DECK_ITEM_ALIGN_MAP: {
    left: string;
    right: string;
    center: string;
};
export declare const DEFAULT_STYLE_POSITION = "auto";
export declare const THEME_FLOOR_COLOR = "rgb(30,60,90)";
export declare const THEME_BACKGROUND_COLOR = "rgb(255,255,255)";
export declare const THEME_DECK_LABEL_TITLE_COLOR = "rgb(255,255,255)";
export declare const THEME_DECK_HEIGHT_SPACING = 200;
export declare const THEME_WINGS_WIDTH = 30;
export declare const THEME_DECK_SEPARATION = 50;
export declare const THEME_SEAT_LABEL_COLOR = "rgb(255,255,255)";
export declare const THEME_SEAT_ARMREST_COLOR = "rgb(185,186,186)";
export declare const THEME_SEAT_STROKE_WIDTH = 1;
export declare const THEME_SEAT_STROKE_COLOR = "rgb(237, 237, 237)";
export declare const THEME_NOT_AVAILABLE_SEATS_COLOR = "dimgrey";
export declare const THEME_BULK_BASE_COLOR = "rgb(186, 199, 213)";
export declare const THEME_BULK_CUT_COLOR = "rgb(148, 168, 190)";
export declare const THEME_BULK_ICON_COLOR = "rgb(70, 81, 94)";
export declare const THEME_FLOOR_BULK_ICON_COLOR = "rgb(206, 216, 237)";
export declare const THEME_FUSELAGE_FILL_COLOR = "lightgray";
export declare const THEME_FUSELAGE_OUTLINE_WIDTH = 12;
export declare const THEME_FUSELAGE_OUTLINE_COLOR = "darkgrey";
export declare const THEME_FUSELAGE_WINDOWS_COLOR = "darkgrey";
export declare const THEME_FUSELAGE_WINGS_COLOR = "darkgrey";
export declare const THEME_FUSELAGE_NOSE_TYPE_DEFAULT = "default";
export declare const THEME_DEFAULT_PASSENGER_BADGE_COLOR = "#1157ce";
export declare const THEME_DEFAULT_PASSENGER_BADGE_LABEL_COLOR = "rgb(255,255,255)";
export declare const THEME_DEFAULT_PASSENGER_BADGE_BORDER_COLOR = "transparent";
export declare const THEME_DEFAULT_FONT_FAMILY = "Montserrat, sans-serif";
export declare const THEME_TOOLTIP_BACKGROUND_COLOR = "rgb(255,255,255)";
export declare const THEME_TOOLTIP_HEADER_COLOR = "#4f6f8f";
export declare const THEME_TOOLTIP_BORDER_COLOR = "rgb(255,255,255)";
export declare const THEME_TOOLTIP_FONT_COLOR = "#4f6f8f";
export declare const THEME_TOOLTIP_ICON_COLOR = "#4f6f8f";
export declare const THEME_TOOLTIP_ICON_BORDER_COLOR = "#4f6f8f";
export declare const THEME_TOOLTIP_ICON_BACKGROUND_COLOR = "#f2f5f8";
export declare const THEME_TOOLTIP_SELECT_BUTTON_TEXT_COLOR = "rgb(255, 255, 255)";
export declare const THEME_TOOLTIP_SELECT_BUTTON_BACKGROUND_COLOR = "rgb(0, 122, 255)";
export declare const THEME_TOOLTIP_CANCEL_BUTTON_TEXT_COLOR = "rgb(0, 24, 51)";
export declare const THEME_TOOLTIP_CANCEL_BUTTON_BACKGROUND_COLOR = "rgb(237, 240, 243)";
export declare const THEME_DECK_SELECTOR_FILL_COLOR = "#fff";
export declare const THEME_DECK_SELECTOR_STROKE_COLOR = "rgba(50, 50, 50, 0.5)";
export declare const THEME_DECK_SELECTOR_SIZE = 25;
export declare const THEME_CABIN_TITLES_WIDTH = 60;
export declare const THEME_CABIN_TITLES_LABEL_COLOR = "#00BFFF";
export declare const THEME_CABIN_TITLES_HIGHLIGHT_COLORS: Record<string, string>;
//# sourceMappingURL=constants.d.ts.map