"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.THEME_WINGS_WIDTH = exports.THEME_TOOLTIP_SELECT_BUTTON_TEXT_COLOR = exports.THEME_TOOLTIP_SELECT_BUTTON_BACKGROUND_COLOR = exports.THEME_TOOLTIP_ICON_COLOR = exports.THEME_TOOLTIP_ICON_BORDER_COLOR = exports.THEME_TOOLTIP_ICON_BACKGROUND_COLOR = exports.THEME_TOOLTIP_HEADER_COLOR = exports.THEME_TOOLTIP_FONT_COLOR = exports.THEME_TOOLTIP_CANCEL_BUTTON_TEXT_COLOR = exports.THEME_TOOLTIP_CANCEL_BUTTON_BACKGROUND_COLOR = exports.THEME_TOOLTIP_BORDER_COLOR = exports.THEME_TOOLTIP_BACKGROUND_COLOR = exports.THEME_SEAT_STROKE_WIDTH = exports.THEME_SEAT_STROKE_COLOR = exports.THEME_SEAT_LABEL_COLOR = exports.THEME_SEAT_ARMREST_COLOR = exports.THEME_NOT_AVAILABLE_SEATS_COLOR = exports.THEME_FUSELAGE_WINGS_COLOR = exports.THEME_FUSELAGE_WINDOWS_COLOR = exports.THEME_FUSELAGE_OUTLINE_WIDTH = exports.THEME_FUSELAGE_OUTLINE_COLOR = exports.THEME_FUSELAGE_NOSE_TYPE_DEFAULT = exports.THEME_FUSELAGE_FILL_COLOR = exports.THEME_FLOOR_COLOR = exports.THEME_FLOOR_BULK_ICON_COLOR = exports.THEME_DEFAULT_PASSENGER_BADGE_LABEL_COLOR = exports.THEME_DEFAULT_PASSENGER_BADGE_COLOR = exports.THEME_DEFAULT_PASSENGER_BADGE_BORDER_COLOR = exports.THEME_DEFAULT_FONT_FAMILY = exports.THEME_DECK_SEPARATION = exports.THEME_DECK_SELECTOR_STROKE_COLOR = exports.THEME_DECK_SELECTOR_SIZE = exports.THEME_DECK_SELECTOR_FILL_COLOR = exports.THEME_DECK_LABEL_TITLE_COLOR = exports.THEME_DECK_HEIGHT_SPACING = exports.THEME_CABIN_TITLES_WIDTH = exports.THEME_CABIN_TITLES_LABEL_COLOR = exports.THEME_CABIN_TITLES_HIGHLIGHT_COLORS = exports.THEME_BULK_ICON_COLOR = exports.THEME_BULK_CUT_COLOR = exports.THEME_BULK_BASE_COLOR = exports.THEME_BACKGROUND_COLOR = exports.SEAT_SIZE_BY_TYPE = exports.SEAT_MAP_WIDTH_TO_WINGS_WIDTH_RATIO = exports.SCALE_TYPES = exports.LOCALES_MAP = exports.FUSELAGE_HEIGHT_TO_WIDTH_RATIO = exports.ENTITY_TYPE_MAP = exports.ENTITY_STATUS_MAP = exports.ENTITY_SCHEME_MAP = exports.DEFAULT_VISIBLE_WINGS = exports.DEFAULT_VISIBLE_HULL = exports.DEFAULT_VISIBLE_CABIN_TITLES = exports.DEFAULT_UNITS = exports.DEFAULT_TOOLTIP_WIDTH = exports.DEFAULT_TOOLTIP_ON_HOVER = exports.DEFAULT_STYLE_POSITION = exports.DEFAULT_SINGLE_DECK_MODE = exports.DEFAULT_SHOW_DECK_SELECTOR = exports.DEFAULT_SEAT_SIZE = exports.DEFAULT_SEAT_PASSENGER_TYPES = exports.DEFAULT_SEAT_MARGIN = exports.DEFAULT_SEAT_MAP_WIDTH = exports.DEFAULT_SEAT_CLASS = exports.DEFAULT_SCALE_TYPE = exports.DEFAULT_RTL = exports.DEFAULT_LANG = exports.DEFAULT_INDEX_ROW_HEIGHT = exports.DEFAULT_HORIZONTAL_LAYOUT = exports.DEFAULT_FEATURES_RENDER_LIMIT = exports.DEFAULT_EXTERNAL_PASSENGER_MANAGEMENT = exports.DEFAULT_DECK_TITLE_HEIGHT = exports.DEFAULT_DECK_PADDING_SIZE = exports.DEFAULT_BUILT_IN_TOOLTIP = exports.DEFAULT_AUTHORIZATION_SCHEME = exports.DECK_ITEM_ALIGN_MAP = exports.CLASS_CODE_MAP = void 0;
var _i18n = require("./i18n.languages");
const SCALE_TYPES = exports.SCALE_TYPES = {
  ZOOM: 'zoom',
  SCALE: 'scale'
};

//#region Entity

const ENTITY_STATUS_MAP = exports.ENTITY_STATUS_MAP = {
  available: 'available',
  unavailable: 'unavailable',
  selected: 'selected',
  preferred: 'preferred',
  extra: 'extra',
  disabled: 'disabled'
};
const ENTITY_TYPE_MAP = exports.ENTITY_TYPE_MAP = {
  seat: 'seat',
  aisle: 'aisle',
  empty: 'empty',
  index: 'index'
};
const ENTITY_SCHEME_MAP = exports.ENTITY_SCHEME_MAP = {
  seat: 'S',
  empty: 'E',
  aisle: '-'
};
const CLASS_CODE_MAP = exports.CLASS_CODE_MAP = {
  f: 'First',
  b: 'Business',
  p: 'Premium economy',
  e: 'Economy'
};

//#endregion

//#region Localization

const LOCALES_MAP = exports.LOCALES_MAP = {
  CN: _i18n.LOCALE_CN,
  DE: _i18n.LOCALE_DE,
  EN: _i18n.LOCALE_EN,
  ES: _i18n.LOCALE_ES,
  PL: _i18n.LOCALE_PL,
  RU: _i18n.LOCALE_RU,
  AR: _i18n.LOCALE_AR,
  // CS uses EN as placeholder — add full Czech translations when needed
  CS: _i18n.LOCALE_EN,
  FR: _i18n.LOCALE_FR,
  PT: _i18n.LOCALE_PT,
  UK: _i18n.LOCALE_UK,
  IT: _i18n.LOCALE_IT,
  JA: _i18n.LOCALE_JA,
  KO: _i18n.LOCALE_KO,
  TR: _i18n.LOCALE_TR,
  VI: _i18n.LOCALE_VI,
  'PT-BR': _i18n.LOCALE_PT_BR,
  NL: _i18n.LOCALE_NL
};

//#endregion

//#region Configuration

const DEFAULT_LANG = exports.DEFAULT_LANG = 'EN';
const DEFAULT_UNITS = exports.DEFAULT_UNITS = 'metric';
const DEFAULT_SCALE_TYPE = exports.DEFAULT_SCALE_TYPE = SCALE_TYPES.SCALE;
const DEFAULT_AUTHORIZATION_SCHEME = exports.DEFAULT_AUTHORIZATION_SCHEME = 'Bearer';
const DEFAULT_SEAT_MARGIN = exports.DEFAULT_SEAT_MARGIN = 3;
const DEFAULT_SEAT_MAP_WIDTH = exports.DEFAULT_SEAT_MAP_WIDTH = 350;
const DEFAULT_HORIZONTAL_LAYOUT = exports.DEFAULT_HORIZONTAL_LAYOUT = false;
const DEFAULT_VISIBLE_HULL = exports.DEFAULT_VISIBLE_HULL = false;
const DEFAULT_VISIBLE_WINGS = exports.DEFAULT_VISIBLE_WINGS = false;
const DEFAULT_VISIBLE_CABIN_TITLES = exports.DEFAULT_VISIBLE_CABIN_TITLES = false;
const DEFAULT_BUILT_IN_TOOLTIP = exports.DEFAULT_BUILT_IN_TOOLTIP = true;
const DEFAULT_EXTERNAL_PASSENGER_MANAGEMENT = exports.DEFAULT_EXTERNAL_PASSENGER_MANAGEMENT = false;
const DEFAULT_SHOW_DECK_SELECTOR = exports.DEFAULT_SHOW_DECK_SELECTOR = true;
const DEFAULT_SINGLE_DECK_MODE = exports.DEFAULT_SINGLE_DECK_MODE = true;
const DEFAULT_TOOLTIP_ON_HOVER = exports.DEFAULT_TOOLTIP_ON_HOVER = false;
const DEFAULT_RTL = exports.DEFAULT_RTL = false;
const DEFAULT_TOOLTIP_WIDTH = exports.DEFAULT_TOOLTIP_WIDTH = 260;
const DEFAULT_SEAT_PASSENGER_TYPES = exports.DEFAULT_SEAT_PASSENGER_TYPES = ['ADT', 'CHD', 'INF'];
const DEFAULT_FEATURES_RENDER_LIMIT = exports.DEFAULT_FEATURES_RENDER_LIMIT = 12;

// FUSELAGE_HEIGHT_TO_WIDTH_RATIO is a sum of Nose SVG h/w and Tail SVG h/w
const FUSELAGE_HEIGHT_TO_WIDTH_RATIO = exports.FUSELAGE_HEIGHT_TO_WIDTH_RATIO = 1.4;
const SEAT_MAP_WIDTH_TO_WINGS_WIDTH_RATIO = exports.SEAT_MAP_WIDTH_TO_WINGS_WIDTH_RATIO = 4;
const SEAT_SIZE_BY_TYPE = exports.SEAT_SIZE_BY_TYPE = [[100, 100], [122, 218], [150, 170], [100, 100], [122, 200], [200, 200], [200, 200], [140, 200], [150, 200], [150, 200], [200, 150], [200, 150], [200, 185], [200, 185], [120, 150], [150, 175], [150, 175], [185, 175], [185, 175], [255, 175], [130, 330], [130, 330], [200, 400], [200, 400], [200, 365], [200, 365], [200, 200], [200, 200], [200, 200], [200, 200], [200, 265], [200, 265], [200, 330], [200, 330], [200, 200], [200, 200], [550, 435], [550, 435], [550, 435], [550, 435], [275, 1230], [275, 1230], [550, 325], [550, 325], [550, 325], [550, 325], [100, 100], [200, 200], [200, 200]];
const DEFAULT_SEAT_SIZE = exports.DEFAULT_SEAT_SIZE = {
  width: 86,
  height: 100
};
const DEFAULT_SEAT_CLASS = exports.DEFAULT_SEAT_CLASS = 'E';
const DEFAULT_DECK_PADDING_SIZE = exports.DEFAULT_DECK_PADDING_SIZE = 10;
const DEFAULT_DECK_TITLE_HEIGHT = exports.DEFAULT_DECK_TITLE_HEIGHT = 80;
const DEFAULT_INDEX_ROW_HEIGHT = exports.DEFAULT_INDEX_ROW_HEIGHT = 120;
const DECK_ITEM_ALIGN_MAP = exports.DECK_ITEM_ALIGN_MAP = {
  left: 'left',
  right: 'right',
  center: 'center'
};
const DEFAULT_STYLE_POSITION = exports.DEFAULT_STYLE_POSITION = 'auto';

//#endregion

//#region Theme

const THEME_FLOOR_COLOR = exports.THEME_FLOOR_COLOR = 'rgb(30,60,90)';
const THEME_BACKGROUND_COLOR = exports.THEME_BACKGROUND_COLOR = 'rgb(255,255,255)';
const THEME_DECK_LABEL_TITLE_COLOR = exports.THEME_DECK_LABEL_TITLE_COLOR = 'rgb(255,255,255)';
const THEME_DECK_HEIGHT_SPACING = exports.THEME_DECK_HEIGHT_SPACING = 200;
const THEME_WINGS_WIDTH = exports.THEME_WINGS_WIDTH = 30;
const THEME_DECK_SEPARATION = exports.THEME_DECK_SEPARATION = 50;
const THEME_SEAT_LABEL_COLOR = exports.THEME_SEAT_LABEL_COLOR = 'rgb(255,255,255)';
const THEME_SEAT_ARMREST_COLOR = exports.THEME_SEAT_ARMREST_COLOR = 'rgb(185,186,186)';
const THEME_SEAT_STROKE_WIDTH = exports.THEME_SEAT_STROKE_WIDTH = 1;
const THEME_SEAT_STROKE_COLOR = exports.THEME_SEAT_STROKE_COLOR = 'rgb(237, 237, 237)';
const THEME_NOT_AVAILABLE_SEATS_COLOR = exports.THEME_NOT_AVAILABLE_SEATS_COLOR = 'dimgrey';
const THEME_BULK_BASE_COLOR = exports.THEME_BULK_BASE_COLOR = 'rgb(186, 199, 213)';
const THEME_BULK_CUT_COLOR = exports.THEME_BULK_CUT_COLOR = 'rgb(148, 168, 190)';
const THEME_BULK_ICON_COLOR = exports.THEME_BULK_ICON_COLOR = 'rgb(70, 81, 94)';
const THEME_FLOOR_BULK_ICON_COLOR = exports.THEME_FLOOR_BULK_ICON_COLOR = 'rgb(206, 216, 237)';
const THEME_FUSELAGE_FILL_COLOR = exports.THEME_FUSELAGE_FILL_COLOR = 'lightgray';
const THEME_FUSELAGE_OUTLINE_WIDTH = exports.THEME_FUSELAGE_OUTLINE_WIDTH = 12;
const THEME_FUSELAGE_OUTLINE_COLOR = exports.THEME_FUSELAGE_OUTLINE_COLOR = 'darkgrey';
const THEME_FUSELAGE_WINDOWS_COLOR = exports.THEME_FUSELAGE_WINDOWS_COLOR = 'darkgrey';
const THEME_FUSELAGE_WINGS_COLOR = exports.THEME_FUSELAGE_WINGS_COLOR = 'darkgrey';
const THEME_FUSELAGE_NOSE_TYPE_DEFAULT = exports.THEME_FUSELAGE_NOSE_TYPE_DEFAULT = 'default';
const THEME_DEFAULT_PASSENGER_BADGE_COLOR = exports.THEME_DEFAULT_PASSENGER_BADGE_COLOR = '#1157ce';
const THEME_DEFAULT_PASSENGER_BADGE_LABEL_COLOR = exports.THEME_DEFAULT_PASSENGER_BADGE_LABEL_COLOR = 'rgb(255,255,255)';
const THEME_DEFAULT_PASSENGER_BADGE_BORDER_COLOR = exports.THEME_DEFAULT_PASSENGER_BADGE_BORDER_COLOR = 'transparent';
const THEME_DEFAULT_FONT_FAMILY = exports.THEME_DEFAULT_FONT_FAMILY = 'Montserrat, sans-serif';
const THEME_TOOLTIP_BACKGROUND_COLOR = exports.THEME_TOOLTIP_BACKGROUND_COLOR = 'rgb(255,255,255)';
const THEME_TOOLTIP_HEADER_COLOR = exports.THEME_TOOLTIP_HEADER_COLOR = '#4f6f8f';
const THEME_TOOLTIP_BORDER_COLOR = exports.THEME_TOOLTIP_BORDER_COLOR = 'rgb(255,255,255)';
const THEME_TOOLTIP_FONT_COLOR = exports.THEME_TOOLTIP_FONT_COLOR = '#4f6f8f';
const THEME_TOOLTIP_ICON_COLOR = exports.THEME_TOOLTIP_ICON_COLOR = '#4f6f8f';
const THEME_TOOLTIP_ICON_BORDER_COLOR = exports.THEME_TOOLTIP_ICON_BORDER_COLOR = '#4f6f8f';
const THEME_TOOLTIP_ICON_BACKGROUND_COLOR = exports.THEME_TOOLTIP_ICON_BACKGROUND_COLOR = '#f2f5f8';
const THEME_TOOLTIP_SELECT_BUTTON_TEXT_COLOR = exports.THEME_TOOLTIP_SELECT_BUTTON_TEXT_COLOR = 'rgb(255, 255, 255)';
const THEME_TOOLTIP_SELECT_BUTTON_BACKGROUND_COLOR = exports.THEME_TOOLTIP_SELECT_BUTTON_BACKGROUND_COLOR = 'rgb(0, 122, 255)';
const THEME_TOOLTIP_CANCEL_BUTTON_TEXT_COLOR = exports.THEME_TOOLTIP_CANCEL_BUTTON_TEXT_COLOR = 'rgb(0, 24, 51)';
const THEME_TOOLTIP_CANCEL_BUTTON_BACKGROUND_COLOR = exports.THEME_TOOLTIP_CANCEL_BUTTON_BACKGROUND_COLOR = 'rgb(237, 240, 243)';
const THEME_DECK_SELECTOR_FILL_COLOR = exports.THEME_DECK_SELECTOR_FILL_COLOR = '#fff';
const THEME_DECK_SELECTOR_STROKE_COLOR = exports.THEME_DECK_SELECTOR_STROKE_COLOR = 'rgba(50, 50, 50, 0.5)';
const THEME_DECK_SELECTOR_SIZE = exports.THEME_DECK_SELECTOR_SIZE = 25;
const THEME_CABIN_TITLES_WIDTH = exports.THEME_CABIN_TITLES_WIDTH = 80;
const THEME_CABIN_TITLES_LABEL_COLOR = exports.THEME_CABIN_TITLES_LABEL_COLOR = '#00BFFF';
const THEME_CABIN_TITLES_HIGHLIGHT_COLORS = exports.THEME_CABIN_TITLES_HIGHLIGHT_COLORS = {
  F: '#BDB76B',
  B: '#FF8C00',
  P: '#8FBC8F',
  E: '#1E90FF'
};
//#endregion
//# sourceMappingURL=constants.js.map